Feature/token manager refactoring
Softeq/XToolkit.RestHttpClient pull request #53
Opened 2021-02-12 08:59 UTC by Synthezator

2021-02-12 09:39 UTC, Synthezator commented on Softeq.XToolkit.DefaultAuthorization/Softeq.XToolkit.DefaultAuthorization.csproj
> +  </ItemGroup>
Check if we can delete this plugin from platform-specific projects

2021-02-12 09:44 UTC, wcoder requested changes

2021-02-12 09:44 UTC, wcoder commented on Softeq.XToolkit.DefaultAuthorization/SecuredHttpServiceGate.cs
> +                _refreshingTokenTask = _sessionApiService.RefreshTokenAsync();
Please revert `deferral` back
The current solution for multiple parallel requests will be trying refresh token for each request.

2021-02-12 09:44 UTC, wcoder commented on Softeq.XToolkit.DefaultAuthorization/SecuredTokenManager.cs
> +        public bool IsTokenExpired => !_tokenExpirationTime.HasValue ||
I think we should ignore case when `tokenExpirationTimespanInSeconds = 0` (unused by auth provider) and return false

2021-02-12 10:01 UTC, Synthezator commented on Softeq.XToolkit.DefaultAuthorization/SecuredTokenManager.cs
> +        private static string DateToString(DateTime dateTime)
Create unit-test: date == StringToDate(DateToString(date))

2021-02-15 22:00 UTC, wcoder approved these changes

2021-02-15 22:04 UTC, wcoder approved these changes

2021-02-16 09:07 UTC, merged